export default function AboutPage() {
  return (
    <div className="flex flex-col items-center justify-center gap-10">
      <div>About</div>
      <div>
        {" "}
        Attestations are signed statements about a person, entity, or thing,
        made by an individual, company, or organization and are one of the
        building blocks of decentralized identity. Praise attestations are
        generated by the Ethereum Attestation Service (EAS) on the{" "}
        <a href="https://www.optimism.io/" target="_blank" rel="noreferrer">
          Optimism
        </a>
        blockchain.
      </div>
      <div>
        The determination of citizenship distribution will eventually be the
        responsibility of Optimism’s two-house governance system 6 and will be
        issued based on the reputation 10 that Optimism Collective members have
        earned. Citizens are meant to represent individual human stakeholders of
        the Collective: builders, users, and community members who are aligned
        with the project’s values and are interested in the long-term benefit of
        the Collective.
      </div>
    </div>
  );
}
