import "./globals.css";

import { ApolloWrapper } from "./ApolloWrapper";
import type { Metadata } from "next";
import { Nav } from "./components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <ApolloWrapper>
          <main className="flex flex-col items-center">
            <div className="pb-20">Optimism Attestation Explorer</div>
            <div className="flex flex-col w-[800px] items-center justify-between font-mono text-sm gap-5">
              {children}
            </div>
          </main>
        </ApolloWrapper>
      </body>
    </html>
  );
}
